### ISSUE TITLE
Error of link - 404 error

### ISSUE THREAD

**Issue by Tipiakus** [akeneo/onboarder-helpcenter#88]
In the page : https://help.akeneo.com/onboarder/articles/retailer-synchronization.html

In the text "When you create a new supplier, you need to [link families and catalog locales](https://help.akeneo.com/onboarder/articles/create-supplier.html) to a supplier. What does it mean and what is the impact?"

The link is wrong and open 404 not found page

**Comment by alexandrelissowski** [comment]
We fixed it. Thanks for the feedback
